# Generated by Django 6.0 on 2025-12-19 03:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rombel',
            options={'ordering': ['jurusan', 'tingkatan', 'nomor']},
        ),
        migrations.AddField(
            model_name='rombel',
            name='jurusan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rombels', to='students.jurusan'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='rombel',
            unique_together={('jurusan', 'tingkatan', 'nomor')},
        ),
    ]
